// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFp_4xwAd3GBWGeWsvePFyqmxeuQl7Lrw',
    appId: '1:164403914518:web:6cb3040f71316c97f05237',
    messagingSenderId: '164403914518',
    projectId: 'ci-cd-3099e',
    authDomain: 'ci-cd-3099e.firebaseapp.com',
    storageBucket: 'ci-cd-3099e.appspot.com',
    measurementId: 'G-FEZ6BGB66K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe9ndGU_3sew6IY8KVDw4SUqHUBzyiPGM',
    appId: '1:164403914518:android:70fea71f0b1776d2f05237',
    messagingSenderId: '164403914518',
    projectId: 'ci-cd-3099e',
    storageBucket: 'ci-cd-3099e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLf1sppNSoNro0RohuCt-Dth6LqNIY3ZI',
    appId: '1:164403914518:ios:6b686bb2fafcccc2f05237',
    messagingSenderId: '164403914518',
    projectId: 'ci-cd-3099e',
    storageBucket: 'ci-cd-3099e.appspot.com',
    iosBundleId: 'com.example.ciCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLf1sppNSoNro0RohuCt-Dth6LqNIY3ZI',
    appId: '1:164403914518:ios:f4c0b054e8450817f05237',
    messagingSenderId: '164403914518',
    projectId: 'ci-cd-3099e',
    storageBucket: 'ci-cd-3099e.appspot.com',
    iosBundleId: 'com.example.ciCd.RunnerTests',
  );
}
