
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release  --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:164403914518:android:70fea71f0b1776d2f05237",
        firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "abdoarfat924@gmail.com",
        release_notes: "first deploy with fastlane in firebase app distribution",
  )
  end
end